### ISSUE TITLE
Windows 10 Compatibility

### ISSUE THREAD

**Issue by asatrash** [oliviercailloux/google-or-tools-java#4]
Hi, Can we use this in windows environment with Eclipse. I have set the Native library location as instructed but getting the following error. 

java.lang.UnsatisfiedLinkError: no jniortools in java.library.path
	at io.github.oliviercailloux.google_or_tools.TestRun.test(TestRun.java:51)

which is at System.loadLibrary("jniortools");

![javabuildpath](https://user-images.githubusercontent.com/4776176/53626776-a4a4c480-3c2c-11e9-895c-ba78a53f8281.PNG)

**Comment by oliviercailloux** [comment]
Question asked to [Google OR-Tools](https://github.com/google/or-tools/issues/1103) for improving doc. I’m still waiting for more complete answers.

**Comment by oliviercailloux** [comment]
Discussion is still ongoing. I updated the instructions a bit (they were primarily worded for linux), and will update more according to the results of the discussion. In the meantime, there’s not much I can do easily to help with library compatibility in general.
For Windows, there should be no problem, just follow the instructions.
