### ISSUE TITLE
few or-tools classes not present

### ISSUE THREAD

**Issue by rishisaraf11** [oliviercailloux/google-or-tools-java#5]
Hi,

I am trying to use maven dependency of your project (thanks for building it) but seems like it's using old or-tools distribution. When running vrp problem (https://developers.google.com/optimization/routing/cvrp) it's not able to find class RoutingIndexManager and main. 

 <dependency>
            <groupId>io.github.oliviercailloux</groupId>
            <artifactId>google-or-tools</artifactId>
            <version>6.7.2</version>
        </dependency>

**Comment by Mizux** [comment]
Last version of ortool is v7.0 and the developer site is based on it

If you look at the GitHub of or-tools you may find vrp samples using the
old API by selecting the v6.10.x branch

Le ven. 29 mars 2019 à 13:17, rishisaraf11 <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
See https://github.com/google/or-tools/tree/v6.10.x/examples/java

**Comment by oliviercailloux** [comment]
@Mizux thanks for the references.

For reasons of time, I do not intend to keep this library systematically up-to-date. I added a word about this in the [README](https://github.com/oliviercailloux/google-or-tools-java#about-more-recent-versions).

**Comment by senzNirojan** [comment]
Use this dependency along with google-or-tools

```
<dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.9.0</version>
</dependency>
```
